title = "Linklog"
url = "https://mondain-dev.github.io/linklog/index.xml"
site = "https://github.com/mondain-dev/linklog"

[[feeds]]
url = "https://quillette.com/rss/"
entry.includes.target = "title"
entry.includes.keyword = "roundup"
link.selector = "a"
link.excludes = ["quillette.com", "twitter.com", "podcasts.apple.com"]

[[feeds]]
url = "http://feeds.feedburner.com/marginalrevolution"
entry.includes.target = "title"
entry.includes.keyword = "assorted link"
link.selector = "a"
link.excludes = ["marginalrevolution.com"]

[[feeds]]
url = "https://braddelong.substack.com/feed"
entry.includes.target = ["title", "content"]
entry.includes.keyword = "briefly noted"
link.selector = "a"
link.excludes = ["braddelong.substack.com","twitter.com", "cdn.substack.com", "substackcdn.com"]
recent = 3
useLinkText = false

[[feeds]]
url = "https://tocqueville21.com/feed/"
entry.includes.target = "title"
entry.includes.keyword = "revue de presse"
link.selector = "a"
link.excludes = ["tocqueville21.com", "twitter.com", "creativecommons.org/licenses", "Wikimedia Commons", "Creative Commons"]
recent = 5
useLinkText = false

[[feeds]]
url = "https://bestoftwitter.substack.com/feed"
link.selector = "a"
link.excludes = ["bestoftwitter.substack.com", "cdn.substack.com"]
recent = 3

[[feeds]]
url = "https://chrisblattman.com/feed/"
entry.includes.target = "title"
entry.includes.keyword = "links i liked"
link.selector = "a"
link.excludes = ["chrisblattman.com"]
recent=3
