title = "Linklog"
url = "https://mondain-dev.github.com/linklog/index.xml"
site = "https://github.com/mondain-dev/linklog"

[[feeds]]
url = "https://quillette.com/rss/"
entry.includes.target = "title"
entry.includes.keyword = "roundup"
link.selector = "a"
link.excludes = ["quillette.com", "twitter.com"]

[[feeds]]
url = "http://feeds.feedburner.com/marginalrevolution"
entry.includes.target = "title"
entry.includes.keyword = "assorted link"
link.selector = "a"
link.excludes = ["marginalrevolution.com"]

[[feeds]]
url = "https://braddelong.substack.com/feed"
entry.includes.target = "title"
entry.includes.keyword = "briefly noted"
link.selector = "a"
link.excludes = ["braddelong.substack.com","twitter.com", "cdn.substack.com"]
recent = 3

[[feeds]]
url = "https://tocqueville21.com/feed/"
entry.includes.target = "title"
entry.includes.keyword = "revue de presse"
link.selector = "a"
link.excludes = ["tocqueville21.com", "twitter.com", "creativecommons.org/licenses", "Wikimedia Commons", "Creative Commons"]
recent = 30
useLinkText = false

[[feeds]]
url = "https://bestoftwitter.substack.com/feed"
link.selector = "a"
link.excludes = ["bestoftwitter.substack.com", "cdn.substack.com"]
recent = 3
