[[feeds]]
url = "https://quillette.com/rss/"
entry.includes.target = "title"
entry.includes.term = "roundup"
link.selector = "a"
link.excludes = ["quillette.com", "twitter.com"]

[[feeds]]
url = "http://feeds.feedburner.com/marginalrevolution"
entry.includes.target = "title"
entry.includes.term = "assorted link"
link.selector = "a"
link.excludes = ["marginalrevolution.com"]


[[feeds]]
url = "https://braddelong.substack.com/feed"
entry.includes.target = "title"
entry.includes.term = "briefly noted"
link.selector = "a"
link.excludes = ["braddelong.substack.com","twitter.com"]

[[feeds]]
url = "https://tocqueville21.com/feed/"
entry.includes.target = "title"
entry.includes.term = "revue de presse"
link.selector = "a"
link.excludes = ["tocqueville21.com", "twitter.com"]
recent = 15

[[feeds]]
url = "https://bestoftwitter.substack.com/feed"
link.selector = "a"
link.excludes = ["bestoftwitter.substack.com"]
recent = 15
